### ISSUE TITLE
Extensionless URL servlet-mapping extension and generated jsf.js

### ISSUE THREAD

**Issue by ehills** [omnifaces/omnifaces#108]
Hi Guys,

Using Omnifaces 1.8.1 or Omnifaces 2.0 I have found the following.

Have noticed that if we have a servlet mapping to a different url-pattern, e.g.:

    <servlet-mapping>
	  <servlet-name>Faces Servlet</servlet-name>
	  <url-pattern>*.gls</url-pattern>
    </servlet-mapping>

And then we implement extensionless URL's with:

    <context-param>
    	<param-name>org.omnifaces.FACES_VIEWS_SCAN_PATHS</param-name>
    	<param-value>/*.xhtml</param-value>
    </context-param>

That the mojarra javascript auto-generated page: jsf.js.xhtml?ln=javax.faces

Is generated with .xhtml. and not .gls (or extensionless) as I would expect.

I have this on a test web app running on Jboss EAP 6.3.3 with no variations in JSF or Weld etc.
Happy to provide further versioning info if it will help.

I did notice that in Omnifaces 2.0 there is a param org.omnifaces.facesviews.facesservletextensions and gave it a param-value of .gls but this seemed to have no affect.

Please let me know if there is something I am missing or not.

Cheers,
Ed

**Comment by arjantijms** [comment]
>Please let me know if there is something I am missing or not.

You're not missing anything, well except for the param (read below).

For extensionless to work correctly and safe the FacesServlet as well the helper filter are mapped to both the extensionless resource paths as well as the encountered extensions.

For instance given two .xhtml files:

/foo.xhtml
/foo/bar.xhtml

Then the FacesServlet is mapped to
"/foo", "/foo/bar", "*.xhtml"

The extension mapping serves 2 purposes:

1. Without it, you'd have a source code exposure vulnerability. I.e. with your declared *.gls mapping, one would be able to request /foo.xhtml anyway and you'd get to see its source code. (see e.g. http://cwe.mitre.org/data/definitions/540.html)

See org.omnifaces.facesviews.FacesViews.addMappings(ServletContext)

We're currently looking if/how we can prevent this vulnerability directly in JSF.


2. JSF 2.2 and below internally still work with extensions, so part of what OmniFaces does is fooling the JSF runtime in believing an extension was used. For this it uses the original extension of the view that is requested without extension. I.e. if you request /foo then OmniFaces remembered that it was originally /foo.xhtml and modifies the request by wrapping it, making it look like to JSF that /foo.xhtml was requested. 

See org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(HttpServletRequest, HttpServletResponse, FilterChain, String)

For JSF 2.3 my plan is to see how we can support this directly in the JSF runtime. See the JSF 2.3 mailing list for discussions about that.

>I did notice that in Omnifaces 2.0 there is a param org.omnifaces.facesviews.facesservletextensions and gave it a param-value of .gls but this seemed to have no affect.

Of course this has no effect, since it's an internal servlet context attribute, it's not a parameter that you set in web.xml ;)

**Comment by ehills** [comment]
> Without it, you'd have a source code exposure vulnerability. I.e. with your declared *.gls mapping, one would be able to request /foo.xhtml anyway and you'd get to see its source code. (see e.g. http://cwe.mitre.org/data/definitions/540.html)

Yep, this is why we use:
```
<security-constraint>
    <display-name>Restrict raw XHTML Documents</display-name>
    <web-resource-collection>
    <web-resource-name>XHTML</web-resource-name>
    <url-pattern>*.xhtml</url-pattern>
    </web-resource-collection>
    <auth-constraint />
</security-constraint>
```

But this then leads to my 403 when javascript tries and uses the generated jsf.js.xhtml ...

> Of course this has no effect, since it's an internal servlet context attribute, it's not a parameter that you set in web.xml ;)

I see! Thanks for pointing that out.

So it doesn't look like omnifaces can get around this problem? Are you able to suggest a workaround at all?

Thanks for the help.
Ed

**Comment by arjantijms** [comment]
>So it doesn't look like omnifaces can get around this problem? Are you able to suggest a workaround at all?

What we typically suggest is mapping the FacesServlet to *.xhtml anyway, and then configuring OmniFaces to send a 404 whenever a scanned view is requested.

Meaning, given the same 2 files as above:

/foo.xhtml
/foo/bar.xhtml

When /foo.xhtml is requested, a 404 is returned, since this is a so-called scanned view.

When jsf.js.xhtml?ln=javax.faces is requested, it's send to the FacesServlet, since it's not a scanned view and the FacesServlet was mapped to *.xhtml.

Note because jsf.js.xhtml is not a scanned view (meaning, it's not encountered during application startup), it's far from trivial to map this an extensionless URL as you mentioned in your first post. With an extra setting it *might* be possible to have JSF use "*.gls" for this, but we actually were looking if we could reduce the number of settings somewhat instead of increasing them ;)

Well, let me know if the above mentioned workaround works for you.

**Comment by ehills** [comment]
Sorry to reply so late! We went with what you have suggested :) Thanks a lot. Feel free to close this issue.

Cheers,
Ed

**Comment by arjantijms** [comment]
Thanks for the followup! :)
