### ISSUE TITLE
Add support for binary files like o:graphicImage

### ISSUE THREAD

**Issue by mores** [omnifaces/omnifaces#162]
I often find a need to stream binary files, like pdf. Can support be added for a new component that would work just like o:graphicImage but support more than just image files ?

**Comment by BalusC** [comment]
For that we already have `Faces#sendFile()` utility methods since OmniFaces 1.0. You can just invoke it directly in bean action method. See also http://showcase.omnifaces.org/utils/Faces

E.g.
```
public void download() throws IOException {
    // ...
    Faces.sendFile(pdfInputStream, true);
}
```
Which you then just invoke by a regular (non-ajax!) command button/link.

This is not possible for image resources which should be embedded in the page. That's exactly why the `<o:graphicImage>` exist.

**Comment by mores** [comment]
Thanks - perhaps I would have found it if the top level menu on the showcase was listed as "Faces.sendFile" instead of just "Faces"

**Comment by BalusC** [comment]
Faces is more than only sendFile(). 

For all available methods, see http://omnifaces.org/docs/javadoc/current/org/omnifaces/util/Faces.html
