### ISSUE TITLE
o:viewParam triggers @NotNull validation error when request parameter is absent in query string

### ISSUE THREAD

**Issue by pholding** [omnifaces/omnifaces#165]
I've hit an issue with o:viewParam which seems to trigger a validation error to be shown in a PrimeFaces Growl component when the variable being set by o:viewParam in the backing bean is annotated with `@NotNull` and the the request parameter is absent in query string.

Based on what I've read in the OmniFaces documentation I believe that one of the benefits of using o:viewParam is that it shouldn't trigger a validation error if the request parameter is absent.

Could you please let me know whether this is this a bug or am I using the o:viewParam component incorrectly?

I'm using OmniFaces version 2.1, PrimeFaces 5.2 and GlassFish 4.1.

The code in my XHTML file is as follows:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:o="http://omnifaces.org/ui">

<f:view contentType="text/html">
	<f:metadata>
		<o:viewParam name="foo" value="#{paramTestController.foo}" />
	</f:metadata>
</f:view>

<h:head>
</h:head>

<h:body>
	<p:growl autoUpdate="true" />
</h:body>

</html>
```

The code in my backing bean is as follows:
```
@Named
@ViewScoped
public class ParamTestController implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@NotNull
	private String foo;

	public String getFoo() {
		return foo;
	}

	public void setFoo(String foo) {
		this.foo = foo;
	}
}
```

**Comment by BalusC** [comment]
Unfortunately, you indeed got it backwards: the f:viewParam doesn't consider any bean validation annotations when the request parameter is absent, which is unexpected. Since OmniFaces 2.0, the o:viewParam fixes this f:viewParam misbehavior by explicitly triggering validation.

The behavior you're observing is thus expected. 

- If the request parameter is not required, remove the `@NotNull`.
- Or, if the property is reused on an input field which is by itself required, create a second property.
- Or, use f:viewParam.

**Comment by djmj** [comment]
Could a _<f:validateBean disabled="true"/>_ help in this case as sibling of _<o:viewParam>_ ?
