### ISSUE TITLE
Does the CombinedResourceHandler respect the resource ordering feature of PrimeFaces?

### ISSUE THREAD

**Issue by stephanrauh** [omnifaces/omnifaces#180]
After an hour of debugging I begin to suspect that the CombinedResourceHandler doesn't respect the resource ordering of PrimeFaces (as described at http://www.mkyong.com/jsf2/primefaces/resource-ordering-in-primefaces/). Is this correct? If so, can you fix it?

**Comment by BalusC** [comment]
> Is this correct? 

That's theoretically indeed possible. 

> If so, can you fix it?

I'd rather not introduce component library specific hacks if there are better ways.

In my humble opinion, the whole PF resource ordering feature is useless. Main reason that it was introduced during PF 3.x was that developers complained that they couldn't get CSS/JS files to be included **after** the auto-included ones. However, no one seems to realize that this can easily be achieved by just putting those resources in `<h:body>` with `target="head"` instead of straight in `<h:head>`. See also a.o. http://stackoverflow.com/q/8768317/157882

The `<f:facet name="first">` in Mkyong example which doesn't cover JSF resources at all can also easily be achieved by `<ui:define>`/`<ui:insert>` or just arranging them logically in the `<h:head>`.

**Comment by stephanrauh** [comment]
Great SO article!

(Like always :) )

**Comment by stephanrauh** [comment]
I have to admit I didn't investigate why our BootsFaces user requested the "first" facet. It just sounded sensible to me. BootsFaces re-orders the JS files to make sure jQuery is always first, so it's fair to give our users a tool to influence resource ordering. I've found a solution that does the trick. It's a bit ugly because it add a non-standard attribute to h:outputStylesheet, but I hope that's not to much of a problem. In case you're interested: more details at http://bootsfaces.net/Staging/layout/resourcemanagement.jsf .

Thanks!
Stephan
