### ISSUE TITLE
massAttribute for multiple attribute-value pairs

### ISSUE THREAD

**Issue by VsevolodGolovanov** [omnifaces/omnifaces#186]
Like in #10, I have a bunch of inputs, but they have multiple common attribute values. With the current o:massAttribute implementation setting them is quite ugly:

```
<o:massAttribute name="value" value="#{filter.value}" target="javax.faces.component.UIInput">
    <o:massAttribute name="required" value="#{filter.required}" target="javax.faces.component.UIInput">
        <o:massAttribute name="disabled" value="#{filter.readOnly}" target="javax.faces.component.UIInput">
            <...>
                <x:inputThis />
                <y:inputThat />
            </...>
        </o:massAttribute>
    </o:massAttribute>
</o:massAttribute>
```

The nesting seems superfluous, the `target` is duplicated. Instead there could be something like:

```
<o:massAttributes target="javax.faces.component.UIInput">
    <o:pair key="value" value="#{filter.value}" />
    <o:pair key="required" value="#{filter.required}" />
    <o:pair key="disabled" value="#{filter.readOnly}" />

    <...>
        <x:inputThis />
        <y:inputThat />
    </...>
</o:massAttributes>
```

Couldn't reuse f:attributes here, since massAttribute has no component. Maybe create a custom tag for passing attributes to tag handlers, but there is already o:tagAttribute, so that could be confusing.

**Comment by BalusC** [comment]
Makes sense.

**Comment by arjantijms** [comment]
Key/values can also be set using the map literal syntax from EL, if we accept `Map` as type.

**Comment by BalusC** [comment]
It only requires EL 3.0.

**Comment by BalusC** [comment]
As we're now on OmniFaces 3.0 which supports EL 3.0, I took a second look. Unfortunately, the map idea didn't work out very well. EL 3.0 API doesn't offer any way to break down the map keys into strings and map values into fullworthy `ValueExpression` instances. Instead, it immediately evaluates those value expressions while `<o:massAttribute>` needs to set the `ValueExpression` in its original and unevaluated form into the component. Otherwise, this won't work for writable properties.

**Comment by BalusC** [comment]
Closing off because it's technically not possible.
