### ISSUE TITLE
Imported constants not accessible during postback with disabled partial state saving

### ISSUE THREAD

**Issue by VsevolodGolovanov** [omnifaces/omnifaces#250]
See [reproducer](https://github.com/omnifaces/omnifaces/files/270077/Imported.constants.not.accessible.during.postback.with.disabled.partial.state.saving.zip).
The same code works fine with OF2.0 or with enabled partial state saving.

**Comment by VsevolodGolovanov** [comment]
Probably caused by the Issue #98 fix.

**Comment by BalusC** [comment]
Can't reproduce #98 anymore with current Mojarra 2.2.13. I've rolled back it (alternative fix was to put in view scope instead of request scope, but this feels wrong). Fix is available in today's [2.4 snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT). Thank you for reporting and improving OmniFaces!

**Comment by VsevolodGolovanov** [comment]
It is fixed, not sure why I thought that rolling back the 98 fix doesn't help.
Maybe forgot to actually build the library when checking or something.
