### ISSUE TITLE
WebXml.createDocument throw exception when web.xml dtd-files isn't accessible

### ISSUE THREAD

**Issue by xtron** [omnifaces/omnifaces#321]
I have web.xml with header:

`<!DOCTYPE web-app PUBLIC
 "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
 "http://java.sun.com/dtd/web-app_2_3.dtd" >
<web-app>
...`

When WebXml.createDocument tries to parse it, when http://java.sun.com/dtd/web-app_2_3.dtd is inaccessible, it throws exception like

`
WebXml failed to initialize. Perhaps your web.xml contains a typo?: org.xml.sax.SAXParseExceptionpublicId: -//Sun Microsystems, Inc.//DTD Web Application 2.3//EN; systemId: http://www.oracle.com/webfolder/technetwork/jsc/dtd/web-app_2_3.dtd; lineNumber: 1; columnNumber: 3; The markup declarations contained or pointed to by the document type declaration must be well-formed.
`

You can change dtd address to something inaccessible to reproduce this error. 

To solve this problem need abilities to disable dtd parsing.

**Comment by BalusC** [comment]
OmniFaces 1.x is designed for Servlet 2.5+ and OmniFaces 2.x is designed for Servlet 3.0+.

The web.xml DTD is only valid until Servlet 2.3. Since Servlet 2.4 (Nov 2003) it's replaced by a XSD.

Get rid of the `<!DOCTYPE ...>` line altogether. It doesn't belong in a Servlet 2.4+ compatible web.xml at all. Your web.xml should at least look like the one shown here: http://stackoverflow.com/a/30082213

**Comment by xtron** [comment]
Thanks, it works!
