### ISSUE TITLE
CombinedResourceHandler on MyFaces 2.2.11

### ISSUE THREAD

**Issue by chongma** [omnifaces/omnifaces#415]
Hi,

I am using TomEE 7.0.3 Plus (MyFaces 2.2.11).  I have tried different OmniFaces versions particularly 1.14 and 2.4.

There seems to be a problem with using OmniFaces CombinedResourceHandler with MyFaces.

There is a test project at https://github.com/chongma/test.  I use the Eclipse IDE and deploy the project onto a TomEE 7.0.3 Plus server.  It currently works as expected with extra dependencies:
```
<dependency>
           <groupId>com.sun.faces</groupId>
            <artifactId>jsf-api</artifactId>
            <version>2.2.13</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.faces</groupId>
            <artifactId>jsf-impl</artifactId>
            <version>2.2.13</version>
            <scope>runtime</scope>
        </dependency>
```
which switch it to Mojarra.  If you remove these dependencies then the CombinedResourceHandler does not work anymore.

Is there a workaround?

Regards,
Matthew

**Comment by BalusC** [comment]
It appears that BootsFaces is adding its resources during `PreRenderViewEvent` instead of as `@ResourceDependency`.

The `CombinedResourceHandler` also runs during `PreRenderViewEvent`, which is the latest possible moment of safe component tree manipulation. However, when BootsFaces is loaded *after* OmniFaces, then the `CombinedResourceHandler` would run before BootsFaces adds its resource dependencies and therefore not have the chance to combine them. It looks like that your MyFaces setup is loading BootsFaces after OmniFaces and that your Mojarra setup is loading OmniFaces before BootsFaces. 

@stephanrauh, perhaps you can explain why BootsFaces adds its resources during `PreRenderViewEvent` instead of as `@ResourceDependency`?

**Comment by chongma** [comment]
I just tried moving OmniFaces above BootsFaces in the dependencies in pom.xml but it didn't seem to make any difference.  Is there another way to change the loading order?

**Comment by BalusC** [comment]
Issue is in BootsFaces side and already reported over there.
