### ISSUE TITLE
Make <o:socket> more dynamic

### ISSUE THREAD

**Issue by jajajaja** [omnifaces/omnifaces#458]
Currently it is impossible to use EL expression as channel name for <o:socket>. 

Also there is no server side API for creation of PushContext with arbitrary name. Only compile-time constants are supported as channel names.

Is it possible to make <o:socket> more dynamic? 

One use case is creation of custom components using <o:socket> underneath.

**Comment by BalusC** [comment]
This is a technical limitation. Just use the `user` attribute for that.

**Comment by jajajaja** [comment]
With 'user' attribute I can not create two <o:socket> with same channel but different handlers on one page.

Could you please provide more details about technical limitations? I've created <o:socket>programmatically in my custom component renderer and it looks like everything works fine. I just want to have such option in public API of omnifaces.

**Comment by BalusC** [comment]
Because EL expressions don't represent constants and channel name has to be a constant, like as the field name of where `@Push` is injected, and the `channel` attribute of the `@Push` annotation.

As to different handlers, check http://omnifaces.org/docs/javadoc/3.1/org/omnifaces/cdi/push/Socket.html#channels for guidelines.
