### ISSUE TITLE
Detect Multiple ResourceHandlers and raise error

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#504]
OmniFaces 2.7
Mojarra 2.2.13

I just recently discovered this issue.  I was having the same problem as described in this issue and stack overflow...
**Issue:** https://github.com/omnifaces/omnifaces/issues/310
**Stack Overflow:** https://stackoverflow.com/questions/40948684/omnifaces-combinedresourcehandler-does-not-combine-javascript-resources

My OmniFaces CombinedResourceHandler was combining my CSS but not my JS on the page.

**Cause:**
I accidentally had the OmniFacesCombinedResourceHandler declared in a _faces-config.xml_ in a Web Fragment JAR and in the _faces-config.xml_ of the web application itself.  Having this declared twice caused the same symptoms as the issue listed above.  Once I removed it from the webapp _faces-config.xml_ it started working again.

**Solution:**
It is possible to detect multiple declarations of a faces-config.xml handler and raise an exception to prevent this from happening in the future?

**Comment by BalusC** [comment]
Implemented in 3.3

**Comment by me90** [comment]
I try to switch from omnifaces 3.2 to 3.3 but i receve an exception
Caused by: java.lang.IllegalArgumentException: More than one fragment with the name [omnifaces] was found. 

In my web xml i don't have  any ConfigureListener entry and in my faces-config.xml nothing else than navigation rules

I use :
Tomcat 9
weld 3.0.Final
MyFaces  2.3.3
Primefaces 7.0
omnifaces 3.3
