### ISSUE TITLE
CombinedResourceHandler: Does not include unload.js

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#547]
Version: **OmniFaces 2.7.4 and 3.3.5**

When using the CombinedResourceHandler it is not including OmniFaces unload.js if using Omni Viewscoped.

Attached is a reproducer you can unzip and run "mvn clean jetty:run-exploded" and then navigate to http://localhost:8080/primefaces-test/test.xhtml

[omnifaces-unload-combined.zip](https://github.com/omnifaces/omnifaces/files/4481652/omnifaces-unload-combined.zip)

You will see in the screenshot unload.js is not being combined.

![image](https://user-images.githubusercontent.com/4399574/79347007-160f0780-7f01-11ea-848c-8f70eb406ca3.png)

This is due to the fact OmniFaces is looking for the Omni script to check whether it need to load the unload.js script but since the script has been renamed by the CombinedResourceHandler this script name does not exist.

https://github.com/omnifaces/omnifaces/blob/279cc5450cf537e38deec6724da34659a73b8b8c/src/main/java/org/omnifaces/cdi/viewscope/ViewScopeManager.java#L222-L232

**Comment by melloware** [comment]
I was able to work around this by adding this to my page

```xml
<h:outputScript library="omnifaces" name="omnifaces.js" target="head" />
```

Now it does detect and does not try to include unload.js

**Comment by BalusC** [comment]
The `context.getApplication().getResourceHandler().isResourceRendered()` was supposed to return true.

**Comment by BalusC** [comment]
Everything is working as intended. The behavior you're observing in your specific example is unfortunately "by design". It's not the fault of `CombinedResourceHandler`.

When any `@ViewScoped` bean is created for the first time during render response, then it's too late to add the `unload.js` as a component resource. So it won't end up being picked up by `CombinedResourceHandler` because it technically runs during `PreRenderViewEvent`.

But when any `@ViewScoped` bean is created for the first time **before** render response, then the `unload.js` is added as a component resource and the `CombinedResourceHandler` will be able to pick up it.

Here's a small change which ensures that the bean is created for the first time before render response, add this to your XHTML:

```
<f:metadata>
    <f:viewAction action="#{testView.init}" />
</f:metadata>
```

**Comment by melloware** [comment]
OK that is what I thought you were going to say.  I am OK with just frontloading omnifaces.js as its a really tiny script anyway.
```xml
<h:outputScript library="omnifaces" name="omnifaces.js" target="head" />
```

Thanks for looking into this!

**Comment by BalusC** [comment]
In the end, you was right. In the following line,

```
if (!context.getApplication().getResourceHandler().isResourceRendered(context, OMNIFACES_LIBRARY_NAME, OMNIFACES_SCRIPT_NAME)) { 
```
The library name and resource name were accidentally swapped.

**Comment by melloware** [comment]
Thanks for fixing!
