### ISSUE TITLE
Comprehension of a method in src/main/java/org/omnifaces/component/input/componentidparam/ConditionalResponseWriter.java

### ISSUE THREAD

**Issue by 129124** [omnifaces/omnifaces#571]
Hi there, when I was reading the code of the function "public void write(char[] cbuf, int off, int len) throws IOException" in src/main/java/org/omnifaces/component/input/componentidparam/ConditionalResponseWriter.java, I found it has no Javadoc. My understanding is “write a   portion of an array of characters. @param cbuf a character array   @param off offset from which to start   reading characters   @param len number   of characters to write". Can you please check if this is correct? Thanks.

**Comment by BalusC** [comment]
It's part of `<o:componentIdParam>` and the `ConditionalResponseWriter` (and `ConditionalWriterListener`) are supposed for internal usage only. In hindsight these should have been hidden from the public API.

Basically the main [javadoc](https://javadoc.io/static/org.omnifaces/omnifaces/4.0-M1/org/omnifaces/component/input/componentidparam/ConditionalResponseWriter.html) contains the answer:

> ResponseWriter intended to work in conjunction with the ComponentIdParam component.
This allows rendering to proceed to the output if the current component matches any of the given ids, otherwise simply does not send anything to the output.

All methods have an override. So if the abovedocumented contition is matched then it continues doing exactly the thing which is documented in the super method, else it won't do anything.
