### ISSUE TITLE
now bean is null

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#590]
I migrated from 3.2 to 3.8.1 and get _null_ when looking up _now_ bean like:

_FacesLocal.evaluateExpressionGet(context, "#{now}");_

- Glassfish 5.0 build 25
- JSF mojarra 2.3.2
- JDK 112

**Comment by BalusC** [comment]
The `#{now}` has in OmniFaces 3.6 been migrated from JSF `<managed-bean>` in `faces-config.xml` to a CDI `@Produces` in `org.omnifaces.config.cdi.DateProducer` class in #546 (and will in OmniFaces 4.0 produce `java.time.Temporal` instead of `java.util.Date` as per #549 ).

I cannot reproduce your problem when placing the line of code in `@PostConstruct` of a CDI managed bean deployed to WildFly 21. I'll have to try GF5 / Mojarra 2.3.2 later.

How does your `beans.xml` look like?

---

I now see that #546 is not mentioned in https://showcase.omnifaces.org/whatsnew .. I'll fix this in next release of showcase.

**Comment by djmj** [comment]
Thanks for your detailed answer and yes i searched the whats-new section if i had missed something. 

I think it is CDI since i have not migrated yet and also have no _beans.xml_ right now. I will test it again in near future.

**Comment by BalusC** [comment]
Okay.

Although it surprises me that OmniFaces 3.x initialization did not fail in this case because it's coded to explicitly fail when CDI bean manager is unavailable.
