### ISSUE TITLE
Add ExceptionSuppressionHandler

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#593]
There is currently no way to suppress both Ajax and non-Ajax exceptions logs without using `FullAjaxExceptionHandler`.
For some applications, such as ones using PrimeFaces Ajax exception handler, it is impossible to use`FullAjaxExceptionHandler`.
For those applications, please add `ExceptionSuppressionHandler ` to support this.
Relates to #592

**Comment by BalusC** [comment]
Just to note:

> without using `FullAjaxExceptionHandler`

The `FullAjaxExceptionHandler` has **no** functionality at all to suppress specific exceptions.

"Suppressing exceptions" is completely different from "Suppressing logging stack traces".

**Comment by lprimak** [comment]
You are correct. The intended functionality was always to suppress the logs. The way I implemented it was to suppress the whole exception, which, while works, is not perhaps the right approach with OmniFaces

The functionality that's needed is to suppress logs. Same functionality that's currently in `FullAjaxExceptionHandler` needs to be extracted into a standalone `ExceptionLoggingSuppressionHandler` so it can be used with PrimeFaces exception handler

**Comment by BalusC** [comment]
The functionality that's currently in `FullAjaxExceptionHandler` wrt suppressing the logging is only related to the `FullAjaxExceptionHandler`'s (and `FacesExceptionHandler`'s) **own** logger (and not to JSF's or Container's logger). So this requirement makes no sense.

All in all, while having your original exception handler in mind, it still looks much like that you actually want to completely suppress the physical exception itself (so that it doesn't at all bubble up into JSF / Container and thus also doesn't get logged by their own loggers). The net effect is that the enduser retrieves a completely blank response of HTTP 200 status (which is technically incorrect but in the end essentially harmless if the root cause boils down to an IO error of type "connection reset by peer" and thus the enduser is already never going to fully retrieve that repsonse).

**Comment by lprimak** [comment]
> The functionality that's currently in FullAjaxExceptionHandler wrt suppressing the logging is only related to the

I'll test again, but the exceptions appear in the logs without `FullAjaxExceptionHandler` but not it in the configuration.
I am not sure why that is if your assumption above is correct.

> All in all, while having your original exception handler in mind, it still looks much like that you actually want to completely 

The issue is triggered by bots and vulnerability scanners out on the internet, not real users, for the most part, and I obviously can't control for that.

**Comment by lprimak** [comment]
For whatever reason, `FullAjaxExceptionHandler` is indeed suppressing the logs.

- clone https://github.com/flowlogix/flowlogix/tree/Issues-Dec2020/jakarta-ee/jee-examples & build
- Deploy on latest Payara
- go to 'exception page' page
- click on 'throw ClosedByInterrupt' button

the exception appears in the server log

However, if `FullAjaxExceptionHandler` is enabled instead of PrimeFaces exception handler, the logs disappear.

**Comment by lprimak** [comment]
> The functionality that's currently in FullAjaxExceptionHandler wrt suppressing the logging is only related to the FullAjaxExceptionHandler's (and FacesExceptionHandler's) own logger (and not to JSF's or Container's logger). So this requirement makes no sense.

This is incorrect (as evidenced by the reproducer above)
Since `FullAjaxExceptionHandler` captures the exception and then decides whether to log them or not, it absolutely controls what logs get suppressed.
Thus triggering a requirement to be able to suppress logging when application is unable to use `FullAjaxExceptionHandler` due to a conflict (such as w/PrimeFaces)

**Comment by BalusC** [comment]
Yes, that's just its job.

The exception handler you're having in mind can not suppress logging (because there's simply nothing to hook on). It should suppress whole exceptions (that JSF/Container ultimately doesn't log them is merely a side effect thereof). The originally imagined name "ExceptionSuppressionHandler" is the correct one. Look at your original "ViewExpiredExceptionHandler". It did exactly this.

**Comment by lprimak** [comment]
Ok, then there needs to be a separate exception suppression handler.
Can you get that into OmniFaces then, please?
thank you!

**Comment by lprimak** [comment]
I have updated the reproducer so logs / exceptions can be testing with or without `responseComplete()` without recompiling. 

The new button that produces the (should be suppressed) exception logs  is `Throw ClosedByInterruptException - no responseComplete()`
