### ISSUE TITLE
mvn clean install no longer installs JAR files

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#595]
With the latest update of 3.x, install no longer works correctly, and JAR file in the local m2 repository is no longer updated

**Comment by BalusC** [comment]
It's working fine for me and at [Travis](https://travis-ci.org/github/omnifaces/omnifaces/jobs/747961206).

Can you please try describing "no longer works correctly" in developer's perspective instead of in enduser's perspective. E.g. copypaste errors from Maven logs here.

I have added a new build plugin to run the vdldoc generator in https://github.com/omnifaces/omnifaces/commit/3f52b2d430f3569722f033a0cdb0744d3e12ffd7. Perhaps it's causing problems for you.

**Comment by lprimak** [comment]
> I have added a new build plugin to run the vdldoc generator in 3f52b2d. Perhaps it's causing problems for you.

This is correct. When I roll back pom.xml prior to this change, install works.

Take a closer look at the logs. I guarantee it's not installing the JARs.
You might not notice because tests are self-contained and do not rely on installing JARs into local M2 repo

**Comment by lprimak** [comment]
The below logs are *not* present in the current 3.x branch:
```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ omnifaces ---
[INFO] Installing /Users/lprimak/Documents/dev/omnifaces/target/omnifaces-3.9-SNAPSHOT.jar to /Users/lprimak/.m2/repository/org/omnifaces/omnifaces/3.9-SNAPSHOT/omnifaces-3.9-SNAPSHOT.jar
[INFO] Installing /Users/lprimak/Documents/dev/omnifaces/pom.xml to /Users/lprimak/.m2/repository/org/omnifaces/omnifaces/3.9-SNAPSHOT/omnifaces-3.9-SNAPSHOT.pom
[INFO] Installing /Users/lprimak/Documents/dev/omnifaces/target/omnifaces-3.9-SNAPSHOT-sources.jar to /Users/lprimak/.m2/repository/org/omnifaces/omnifaces/3.9-SNAPSHOT/omnifaces-3.9-SNAPSHOT-sources.jar
[INFO] Installing /Users/lprimak/Documents/dev/omnifaces/target/omnifaces-3.9-SNAPSHOT-javadoc.jar to /Users/lprimak/.m2/repository/org/omnifaces/omnifaces/3.9-SNAPSHOT/omnifaces-3.9-SNAPSHOT-javadoc.jar
```

**Comment by BalusC** [comment]
Okay, I've removed it. I'll later take a closer look as to what exactly is causing this.
