### ISSUE TITLE
Jakarta 9, Glassfish 6.0 and OmniFaces 4.0

### ISSUE THREAD

**Issue by abu-al-sadeq** [omnifaces/omnifaces#609]
Greetings,

So I am migrating to Jakarta 9 and thus updating OF to 4.0.
However I feel a bit lost and thought maybe you can shine some light on me, OmniFaces 4 (the jakartafied version of 3.9) requires java 11. and the only application server which runs Jakarta 9 I can find now is glassfish 6.0. ANd glassfish 6 does not support Java 11..
What did I miss in this?! Can you guide me to solve this missing piece?

Thanks!

**Comment by abu-al-sadeq** [comment]
I found out that apache tomcat 10 supports jakarta 9, but I get the error:

`
Caused by: java.lang.IllegalStateException: OmniFaces failed to initialize! Report an issue to OmniFaces.
		at org.omnifaces.ApplicationInitializer.onStartup(ApplicationInitializer.java:58)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5115)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 43 more
	Caused by: java.lang.NoClassDefFoundError: jakarta/faces/application/ViewHandler
		at org.omnifaces.ApplicationInitializer.onStartup(ApplicationInitializer.java:55)
		... 45 more
`

**Comment by BalusC** [comment]
GlassFish 6.0.0 is indeed an unfortunate case. Ignore it for now. Wait for it to have a Java 11+ compatible server ready, which I guess will become available as 6.1.0. In the meanwhile, pick another server (you can find in our pom.xml a list of tested servers, [here](https://travis-ci.org/github/omnifaces/omnifaces/builds/755932507) you can see test results).

JBoss WildFly 22 "Preview" was already released a few weeks ago. IBM OpenLiberty 21 is already available as beta (currently not yet covered by our IT, but will be soon). TomEE 9.x is also already ready since a couple of months, but whilst its current M3 version supports jakarta.* namespace, it unfortunately doesn't yet support https://jakarta.ee/* URLs in deployment descriptors (meaning you can only use old http://xmlns.jcp.org/* URLs in DD files).

Tomcat is technically speaking **not** a full fledged Jakarta EE server, but it's a barebones servletcontainer, offering only JSP, Servlet, EL, WS and JASIC out the box. It doesn't support other parts of JEE. You need to manually install at least JSF, CDI, JSTL, JSONP and BV in order to get JSF to run. You can find installation instructions for that in [Mojarra's github homepage](https://github.com/eclipse-ee4j/mojarra).

If you really want to use GlassFish 6.0.0, then pick for now OmniFaces 4.0-M4, it was (temporarily) compiled using Java 1.8. All newer ones are indeed Java 11.

**Comment by arjantijms** [comment]
> GlassFish 6.0.0 is indeed an unfortunate case. Ignore it for now. Wait for it to have a Java 11+ compatible server ready, which I guess will become available as 6.1.0. 

It's very unfortunate,  but we only had/have a few people working on it. If anyone wants to help out, that would be really appreciated.

**Comment by abu-al-sadeq** [comment]
Thanks a lot for the clarification.

I will use then OmniFaces 4.0-M4 for now with glassfish 6.

Hopefully the team can finish working on the support for jdk11. 

I don't have any experience in application server development. If you can provide me with some insight about the requirements, perhaps I can help.
