### ISSUE TITLE
o:inputFile + f:ajax showcase not working

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#611]
[ShowCase Demo](https://showcase.omnifaces.org/components/inputFile#demo)

I've made many tests with plain h:inputFile and omnifaces o:inputFile
both have problems with f:ajax

**Comment by BalusC** [comment]
Show case demo is working for me in Chrome 87 and FireFox 84. I'm able to select an image file of max 1MiB and getting it to display in section below the button. Below screenshot is from Chrome.

![image](https://user-images.githubusercontent.com/173372/105990088-644c5c00-6078-11eb-972c-23d251d71511.png)

You need to describe "not working" more clearly. Try to describe the problem in developer's perspective instead of in enduser's perspective. E.g. describe the expected/unexpected parts of the HTTP request and/or response.

**Comment by pizzi80** [comment]
Linux Fedora 33 

1) Firefox 84   => OK
2) Chrome 88 => does not show the picture after upload 

Windows 10

1) Firefox 84   => OK
2) Chrome 87 => does not show the picture after upload 

with the developer tools I see the multipart POST and GET requests to server
both with chrome and firefox

The strange thing is that with Chrome POST and GET are inverted 
and the GET request never ends ... o_O

![Schermata da 2021-01-27 15-22-17](https://user-images.githubusercontent.com/17908214/106004974-09d0f100-60b4-11eb-95c5-4ebefe0c537b.png)


If I inspect the response of the POST request I can see the classic JSF Ajax response with the modified
part of HTML both with Chrome and Firefox


but with Chrome the GET request never ends 

![Schermata da 2021-01-27 15-32-55](https://user-images.githubusercontent.com/17908214/106006273-57019280-60b5-11eb-98f4-1df98861572a.png)

**Comment by BalusC** [comment]
The GET one is a fetch from sw.js (ServiceWorker). Shouldn't be a problem (it's not by default enabled, it's only enabled when you have a `WebAppManifest` impl as per https://showcase.omnifaces.org/resourcehandlers/PWAResourceHandler ).

Does your Ajax response contain the `<img>` with base64 content in its `src`? (highlighted in below screenshot)
![image](https://user-images.githubusercontent.com/173372/106258228-f2991d00-61f3-11eb-9a31-2a71396e4ecf.png)

**Comment by pizzi80** [comment]
> Does your Ajax response contain the <img> with base64 content in its src? (highlighted in below screenshot)

Yes it does but  the render does not start

I have the same problem and the same output with <h:inputFile 

Firefox is ok but Chrome does not execute the ajax render phase

it seems a core JSF ajax problem:

I have a CDI backing bean that save the input file to disk inside the directory "upload"

`<h:form id="upload" enctype="multipart/form-data" >
    <h:inputFile id="image" value="#{uploadImage.file}" >
        <f:ajax execute="@form" listener="#{uploadImage.upload}" render=":preview" />
    </h:inputFile>
</h:form>
		
<h:panelGroup id="preview">
    #{now.time}
    #{uploadImage.outputFile}
    <h:graphicImage value="/upload/#{uploadImage.outputFile}" width="600" rendered="#{uploadImage.outputFile ne null}" />
</h:panelGroup>`

**Comment by BalusC** [comment]
Just tried with Mojarra 2.3.14 on Tomcat 9.0.39, also norepro in Chrome 88.

I suggest to set project stage to `Development` (so that the `jsf.js` will be included in unminified form) and then put a debug breakpoint somewhere inside `response: function response(request, context) {}` so you can analyze what's (not) happening.

![image](https://user-images.githubusercontent.com/173372/106384213-1ef19c80-63a0-11eb-842d-4fc33c7e6ee6.png)

In any case, this is not an OmniFaces issue, so closing off.

**Comment by pizzi80** [comment]
Thanks @BalusC 

I've reported this to Mojarra 

https://github.com/eclipse-ee4j/mojarra/issues/4828
