### ISSUE TITLE
GzipResponseFilter: OpenLiberty not zipping JS

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#620]
**OmniFaces:** 3.10.1
**OpenLiberty:** 21.0

I have been using `CombinedResourceHandler` and `GzipResponseFilter` for years with great success.  I am testing an app on OpenLiberty 21 as a runnable JAR.  The same WAR file running in Wildfly compresses the JS from 1.3MB down to 300K.

```xml
    <!-- Apply GZIP compression on responses whenever applicable -->
    <filter>
        <filter-name>GzipResponseFilter</filter-name>
        <filter-class>org.omnifaces.filter.GzipResponseFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>GzipResponseFilter</filter-name>
        <servlet-name>Faces Servlet</servlet-name>
    </filter-mapping>
```

The combined CSS is getting GZIPPED but the Combined JS is not.

Here is the CSS the Content Encoding is `gzip`
![image](https://user-images.githubusercontent.com/4399574/109807949-89db0100-7bf4-11eb-9eab-f31cae0649a5.png)

Here is the JS and the Content Encoding is NOT gzip and I can see the JS is uncompressed and is the full 1.3MB...
![image](https://user-images.githubusercontent.com/4399574/109808052-a840fc80-7bf4-11eb-8fcc-0a71f5d299d1.png)

**Comment by BalusC** [comment]
`Content-Type: application/x-javascript` is indeed not recognized by `GzipResponseFilter`.

I'll fix in next version. For now you can work-around it by adding new `<init-param>` of `mimetypes` conform documentation: https://showcase.omnifaces.org/filters/GzipResponseFilter

Alternatively, try adding `<mime-mapping>` to `web.xml` which explicitly maps `*.js` to `application/javascript` so that it's covered by default suppported mimetypes of `GzipResponseFilter`.

**Comment by melloware** [comment]
Great support works like a charm!  thanks for fixing in future version.
