### ISSUE TITLE
inputFile message: support for PrimeFaces-inspired search expressions

### ISSUE THREAD

**Issue by flange-ipb** [omnifaces/omnifaces#625]
Hi!
I'm trying to use search expressions like `@next` and `@previous` in a message's for attribute to reference an `<o:inputFile>`, but rendering fails with
> java.lang.IllegalStateException - o:inputFile client side validation of maxsize requires a message(s) component with a fixed ID.
at org.omnifaces.component.input.InputFile.validateHierarchy(InputFile.java:420)

Example:
```xml
<o:inputFile id="inputJsonFileId" value="#{testBean.jsonFile}"
	maxsize="#{1024 * 1024}" />
<p:message id="messageInputJsonFileId" for="@previous" />
```
Any chance to get this supported?

Thanks,
Frank

**Comment by BalusC** [comment]
Hmm, looks like PrimeFaces is still using its native search expression resolver instead of the JSF 2.3-provided facility (see also https://arjan-tijms.omnifaces.org/p/jsf-23.html#1238). Unsure why it is doing that. Perhaps it's trying to be backwards compatible with JSF 2.2 or older? @melloware can you tell?

Supporting this on o:inputFile would require a PrimeFaces-specific dependency or hack and I'd rather not for this specific case which is trivially workaroundable.

**Comment by melloware** [comment]
I will check.  I have a feeling it was for backwards compatibility.

**Comment by tandraschko** [comment]
@BalusC yep, we are doing this for backward compatibility.
We only have one project for JSF 2.0-3.0 currently. Maybe we can remove this stuff for 4.0. Maybe we need 2 seperate java projects then and reuse JS/CSS.

**Comment by BalusC** [comment]
Fixed. It will however require JSF 2.3 so I haven't fixed it for 2.x but only for 3.x.

Fortunately the JSF 2.3 native search expression framework also supports `@previous` out the box, so your specific case will continue to work. But it you're using a search expression keyword which is only supported in PrimeFaces and not in JSF 2.3, then it would still fail.
