### ISSUE TITLE
o:inputFile doesn't work on Chrome with Google Analytics Opt-out Add-on (by Google) extension

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#656]
https://showcase.omnifaces.org/components/inputFile

it should rerender the <o:graphicImage but it doesn't work

```
<o:graphicImage value="#{uploadImageBean.content}" dataURI="true" width="600" 
        rendered="#{not empty uploadImageBean.content}" />
```

**Comment by BalusC** [comment]
Works for me at the moment.

![image](https://user-images.githubusercontent.com/173372/146581830-727a5436-40dd-4f95-8954-6b7663f62876.png)

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

**Comment by pizzi80** [comment]
OMG ...after some debugging on Windows and Linux it turns out that was the following Chrome Extension:

https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh

**Comment by BalusC** [comment]
Reproduced. But nothing which I can do from OmniFaces side on. I suspect the extension didn't expect/like iframe based "ajax" file uploads. You might want to report this issue to them. Best what we could do is to improve standard JSF itself to use FormData API instead of iframe if available. The iframe trick is rather dated these days as the browser support for FormData API is pretty wide these days: https://caniuse.com/mdn-api_formdata
