### ISSUE TITLE
Adding OmniFaces to JSF 2.2 with Weld app gives NullPointerException

### ISSUE THREAD

**Issue by SlavikZ** [omnifaces/omnifaces#75]
I have problem similar to issue #8 , but in configuration with Tomcat7+ Mojarra/Weld. If I add OmniFaces to my pom file I get NullPointerException during handleNavigation call:

```
javax.servlet.ServletException
    javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

root cause

java.lang.NullPointerException
    com.sun.faces.application.NavigationHandlerImpl.determineViewFromActionOutcome(NavigationHandlerImpl.java:1341)
    com.sun.faces.application.NavigationHandlerImpl.findWildCardMatch(NavigationHandlerImpl.java:661)
    com.sun.faces.application.NavigationHandlerImpl.getViewId(NavigationHandlerImpl.java:483)
    com.sun.faces.application.NavigationHandlerImpl.handleNavigation(NavigationHandlerImpl.java:190)
    com.sun.faces.application.NavigationHandlerImpl.handleNavigation(NavigationHandlerImpl.java:183)
...
```

Here is my test project: https://copy.com/vzqqkonLSEbPkzzS
Calling `go.xhtml` without OmniFaces works OK, but with OmniFaces I get NullPointerException.

**Comment by daniel-souza** [comment]
Hi BlausC, your workarround works fine! Thanks.
I Believed that the problem was with Apache Deltaspike, because the error "NullPointerException" shows some causes with ViewAccessScoped navigation, even if don't use this annotation.
When I removed the Deltaspike libraries of my project, I got the same error message of this issue.
With this workarround inside the WeldApplication, now everthing works fine, even if I use the Deltaspike annotations.
