### ISSUE TITLE
ValidateMultiple: is it correct to invalidate unrendered fields?

### ISSUE THREAD

**Issue by NicolaIsotta** [omnifaces/omnifaces#783]
Consider this example:
```xhtml
<h:inputText id="text1"/>
<h:inputText id="text2"/>
<h:inputText id="text3" rendered="#{myBean.shouldRender}"/>
<o:validateMultiple id="multipleValidator" validator="#{myBean.validator}" components="text1 text2 text3"/>
```
where `#{myBean.shouldRender}` evaluates to `false`.
Suppose the form is submitted and `#{myBean.validator}` returns `false`. All referenced components will be invalidated, including `text3`, even if it's not rendered. Then, when the form is submitted and components are collected here:
https://github.com/omnifaces/omnifaces/blob/dbe8012da9543918aba1ae46fc82051633779147/src/main/java/org/omnifaces/component/validator/ValidateMultipleFields.java#L255-L263
`text3` will be invalid because its status is not resetted, so `#{myBean.validator}` won't be called anymore:
https://github.com/omnifaces/omnifaces/blob/dbe8012da9543918aba1ae46fc82051633779147/src/main/java/org/omnifaces/component/validator/ValidateMultipleFields.java#L213-L217

I think there are two possible solutions:

- do not collect components if they are not rendered
- do not invalidate components if they are not rendered

I can prepare a PR if needed. WDYT?

**Comment by BalusC** [comment]
Okay, the main javadoc says this:

>  When a target component is <code>disabled="true"</code>, <code>readonly="true"</code> or <code>rendered="false"</code>,
>  then the <code>values</code> argument of {@link #validateValues(FacesContext, List, List)}, will instead contain the
 > initial model value. This is quite useful when you need to validate against an existing model.

We therefore need to collect components regardless. The "do not invalidate components if they are not rendered" solution therefore makes most sense.

And the collectComponents() javadoc says this:

> Collect the input components. Only those which are an instance of {@link UIInput}, are rendered, not disabled nor
> readonly will be returned. If at least one of them has already been validated and is been marked invalid, then an
> empty collection will be returned.

The collectComponents() javadoc therefore needs update/clarification.

**Comment by BalusC** [comment]
Merged, thank you very much for improving OmniFaces!

**Comment by bsanders1979** [comment]
Hello,
I landed here by searching for "collectComponents". I am testing out our much overdue upgrade. I have this screen with 2 different passwords. Each password has a confirmation box and the rule is that the passwords must be different. In order to change a password, the user must check the box (this prevents a lot of guesswork) to enable each input pair. Anyhow, this validation should only be done when both are enabled. I suppose I could disable the validator itself by looking at the checkboxes, but that feels like a band-aid. If that's what I have to do (for now?), then so be it. In the old code, the `if (!Components.isEditable(input))` bit is what's causing the difference in behavior. Please advise. Thanks!

PS: The line was removed in v3.0
I did end up using disabled on the validator. I reviewed the file history and can see where the logic was effectively moved to. But, if anything, I suppose this is another use-case to consider.

![image](https://github.com/omnifaces/omnifaces/assets/1124276/cad05695-6bf5-4988-869b-e5d38f90adf2)
![image](https://github.com/omnifaces/omnifaces/assets/1124276/8b9373d3-8405-4ac0-8b04-bb3ecf413d1c)
![image](https://github.com/omnifaces/omnifaces/assets/1124276/b1aee693-3bfc-4365-b520-7ae4e0a53bdd)

**Comment by NicolaIsotta** [comment]
Have you tried including the checkboxes in the validated components?
