### ISSUE TITLE
Json: Encode Java14 Record objects

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#817]
@BalusC you might want to backport this MyFaces change since it was originally from your code here.

https://github.com/apache/myfaces/pull/711

**Comment by BalusC** [comment]
That'll be OmniFaces.next because OmniFaces 4.x is tied to Java 11.

**Comment by melloware** [comment]
Yep I thought so just wanted to leave you this reminder. Thanks!

**Comment by pizzi80** [comment]
> @BalusC you might want to backport this MyFaces change since it was originally from your code here.
> 
> [apache/myfaces#711](https://github.com/apache/myfaces/pull/711)

LOL for the test ...  `record Pokemon` ... :smile:

**Comment by pizzi80** [comment]
> That'll be OmniFaces.next because OmniFaces 4.x is tied to Java 11.

I understand the major version thing, 
but, at the moment, the minimun java version support
is becoming a very limiting thing for open source projects

I can understand Java 8 -> Java 11
But after that there are no problems to upgrade java ...

**Comment by BalusC** [comment]
I get that but the thing is that Jakarta EE 10 itself (with Faces 4.0) requires a minimum of Java 11 and OmniFaces aims to be least intrusive.

Jakarta EE 11 (with Faces 4.1) will jump to Java 17 and soon be released, and then we can release OmniFaces 5.x with the same minimum requirement as well.

**Comment by BalusC** [comment]
I started 5.x branch already.

**Comment by pizzi80** [comment]
@BalusC you're awesome!

I would like to clarify that my comment wasn't an attack against you!
Sometimes I'm a bit direct, but It's only because 
I'm too lazy to elaborate a more formal response..

I'm also a bit irritated because I had to fork 4 o 5 projects 
to have a stable and future ready framework to develop webapps. 

I'm actually on Java 21 and very soon I will upgrade 
to Java 22 because I need the new FFM

So when I see that Jakarta EE 11 it's releasing on Q2 2024 
and targeting a 2021's JVM ................................. :japanese_ogre: 

This will mine the productivity of committers and a lot of people 
will never start to contribute

**Comment by melloware** [comment]
@BalusC you rock!
