### ISSUE TITLE
ViewScopeContext not thread-safe

### ISSUE THREAD

**Issue by zeners** [omnifaces/omnifaces#823]
ViewScoped Beans are sometimes created in the same View multiple times, if they are accessed from parallel threads.

Seems that the [ViewScopeContext.get(Contextual<T>,  CreationalContext<T>)](https://github.com/omnifaces/omnifaces/blob/dbc1993bc074e7ecfa453a6857444bd33b46ba4e/src/main/java/org/omnifaces/cdi/viewscope/ViewScopeContext.java#L71) is not thread-safe.

May you please fix it?
Do you need a sample to reproduce?

**Comment by BalusC** [comment]
A reproducer is welcome because this diverts from the default/specified behavior. As per spec, HTTP requests in servlet containers are single threaded and Faces Ajax requests are queued. So something else is going on beyond the responsibility of Servlet/Faces spec which usually in turn needs to be synchronized.

**Comment by zeners** [comment]
yes, we manually start async threads with copied FacesContext

i will add a reproducer

**Comment by BalusC** [comment]
Then more things in the Faces spec/impl shall need to be synchronized because for example the component tree and state restoring/saving is also not thread safe by definition. You should probably take a step back and find a different solution for the problem for which you thought that manually starting async threads with copied FacesContext would be the correct solution.

Reproducer is not needed, point is taken. This is just not the correct usage of Faces.

**Comment by zeners** [comment]
@BalusC the component tree isn't a issue, rendering only take place on request threads

Maybe not correct usage, but the only point to kick a nice feature

**Comment by BalusC** [comment]
Can you tell more about that feature?

**Comment by zeners** [comment]
We speed up the showing up of pages while background threads doing longer running load / calculations only for parts, but in parallel. These tasks only need the beans, not the component tree.

i will create a reproducer, so it can show up.

**Comment by BalusC** [comment]
Have you already looked at `@Eager`? https://showcase.omnifaces.org/cdi/Eager

**Comment by BalusC** [comment]
Here's a SO Q&A with a concrete example: https://stackoverflow.com/q/6149919, check section "Asynchronously fetch the model on page load". This will be a tad faster in combination with `@Eager` as seen on similar example at https://balusc.omnifaces.org/2014/06/omnifaces-18-released.html, under section "Eagerly instantiate a CDI managed bean".

I believe this is the more correct solution to the problem you was trying to solve.

**Comment by zeners** [comment]
if i understand correctly, Eager instantiate each annotated ViewScoped Bean at creation of the Scope. Unfortunately that doesn't fit to our scenario.

Thanks for take a look and the hints.

**Comment by melloware** [comment]
@zeners no not EagerScoped your ViewScoped beans....definitely read BalusC answer in that Stack Overflow. Its the "correct" way to do what you are trying to do.

**Comment by BalusC** [comment]
> *Eager instantiate each annotated ViewScoped Bean at creation of the Scope*

No, at start of the HTTP request. Far before all filters and servlets.

I however do personally agree that the logic in ViewScopeContext#get() can be a tad more robust like computeIfAbsent so I'll take a look at that later. But on the other hand, you should probably synchronize the threads on your side by view ID or bean ID as well, or to rewrite code to instead manage them from bean's `@PostConstruct` as seen in previous code examples.

**Comment by zeners** [comment]
@BalusC thank you
