### ISSUE TITLE
o:deferredScript integrity optional?

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#826]
during development if I change a js file the integrity no longer matches

I didn't find a way to disable the integrity computation because it's cached
inside a Map with computeIfAbsent

**Comment by BalusC** [comment]
Fixed. It's unfortunately not efficiently possible to clear the integrity before the "last modified" timestamp of the resource is calculated (which only happens during generating the resource URL) and hence you'll need to refresh twice instead of only once. But it's better than never being able to reset it by refreshing.
