### ISSUE TITLE
Jakarta 10 Compatibility

### ISSUE THREAD

**Issue by JanHuege** [omnifaces/omnifaces#863]
We are in the process of migrating an old Java EE 7 project to Jakarta 10. Omnifaces 4.0.4 seems to keep expecting javax.faces imports (ClassNotFoundExceptions) using Wildfly 33.

Are there any steps that we are missing? We upgraded Primefaces for example using their jakarta maven classifier. Omnifaces Docs do not mention any steps that are required. At least we did not find them yet.

Any suggestions?

**Comment by BalusC** [comment]
OmniFaces 4.0.4 [does not exist](https://mvnrepository.com/artifact/org.omnifaces/omnifaces). Please doublecheck the OmniFaces version being used.

OmniFaces 4.x is fully runtime compatible with Jakarta EE 10 / Faces 4.0 since version 4.0-M12 which was released November 21, 2021. 

The currently available latest 4.x version is 4.5.1. Please give it a try.

If in vain, please post the full stack trace.

**Comment by JanHuege** [comment]
Sorry using V4.5.1

**Comment by BalusC** [comment]
Please post the full stack trace.

To prove that OmniFaces is fully jakartified, the integration tests run on jakartified environments and they all pass: https://github.com/omnifaces/omnifaces/actions/runs/10964891707

**Comment by JanHuege** [comment]
Ok I think we found the issue. Old sources are a pain to work with if they are not yours. Anyways thanks for being our rubberduck... 

In the end it was an issue with a package not being referenced correctly in the multimodule maven structure.

Closing :)

**Comment by BalusC** [comment]
Yeah the answer would be in the stack trace. Glad you figured out it.

No problem :)
