### ISSUE TITLE
ViewExpiredException on error page defined in web.xml

### ISSUE THREAD

**Issue by skybber** [omnifaces/omnifaces#865]
We encountered an issue with forwarding to an error page, which may not necessarily be related to Omnifaces, but it's at least worth reporting. The error occurs in the `FullAjaxExceptionHandler` when the request is not an Ajax request:

```
		if (!context.getPartialViewContext().isAjaxRequest())
		{
			throw new FacesException(exception); // Not an ajax request, let default web.xml error page mechanism or
																						// FacesExceptionFilter do its job.
		}
```

The exception is then processed by Tomcat, which forwards to the JSF error page. The JSF servlet (MyFaces), for some mysterious reason (there is a ViewState from the previous page in the request), attempts to perform a Restore View, and this results in an error. If the initial page is stateless, the error does not occur ! I can't determine whose side the issue is on—whether it’s Tomcat, MyFaces, or Omnifaces? I'm using Tomcat 10, Omnifaces 4.4, MyFaces 4.

**Comment by BalusC** [comment]
Norepro.

A reproducer is helpful. This case is also already covered by `FullAjaxExceptionHandlerIT`: https://github.com/omnifaces/omnifaces/blob/4.4/src/test/java/org/omnifaces/test/exceptionhandler/fullajaxexceptionhandler/FullAjaxExceptionHandlerIT.java#L179-L202

**Comment by pizzi80** [comment]
I spent days over Exception handling because it's not well standardized 

Take a look at this thread: https://github.com/omnifaces/omnifaces/issues/790

I don't remember all the possibile situations but my final solution was 
to override the `FullAjaxExceptionHandler` 
to handle both ajax and non-ajax exceptions

I use your same stack but with Mojarra instead of MyFaces

try also to upgrade to OmniFaces 4.5.1

**Comment by BalusC** [comment]
Still, a reproducer is helpful because I cannot reproduce this. Most probably your error page is extending from a template which submits a form during page load via e.g. commandScript/remoteCommand. You should disable/remove such forms then. The error page may not contain any stateful forms at all even not a logout form.

**Comment by skybber** [comment]
I've prepared repo for reproducing this issue https://github.com/skybber/of-issue-865 , but it needs some investigation since it does not reproduce the problem :)

**Comment by skybber** [comment]
Reproducer is working now, I've added to `web.xml`:

```
  <error-page>
    <exception-type>java.lang.Throwable</exception-type>
    <location>/errorpages/500.jsf</location>
  </error-page>
```

`StandardHostValve` from Tomcat 10.1.X forwards request to JSF servlet, and the processing fails in RestoreViewExecutor with `viewRoot == null`.

**Comment by BalusC** [comment]
You've hit an incredible corner case there.

Jakarta Faces normally won't restore the view of an error page, but fails to do so when the servlet container (Tomcat) doesn't set the `jakarta.servlet.error.message` request attribute with a non-`null` value. 

When using `<exception-type>java.lang.Throwable</exception-type>` instead of `<error-code>500</error-code>` the `jakarta.servlet.error.message` request attribute becomes `null` when the thrown exception has no message.

When using `<error-code>500</error-code>` the `jakarta.servlet.error.message` request attribute becomes an empty string when the thrown exception has no message.

So, there are 2 solutions in your specific case: 
- use `<error-code>500</error-code>` instead of `<exception-type>java.lang.Throwable</exception-type>` (this is coincidentally also recommended in the [FullAjaxExceptionHandler documentation](https://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler), but for a different reason: being able to deal with other exception types such as `ViewExpiredException`).
- or, throw with an explicit message as in `throw new RuntimeException("message")` instead of `throw new RuntimeException()`.

As to the Faces way of detecting the error page, the Faces spec doesn't say anything about checking specifically the `jakarta.servlet.error.message` request attribute in the [Restore View](https://jakarta.ee/specifications/faces/4.0/jakarta-faces-4.0#a404) section and yet both Mojarra and MyFaces check for this. IMO it should have checked `HttpServletRequest#getDispatcherType()` instead but it has compatibility implications for non-servlet environments such as portlets, which Jakarta Faces also should be supporting. Probably `jakarta.servlet.error.status` or `jakarta.servlet.error.request_uri` had been a better attribute to check as these are never `null`.

On the other hand, Tomcat could also have been wrong by setting the `jakarta.servlet.error.message` request attribute with a `null` value instead of an empty string because the Servlet spec says that these request attributes "[must be set](https://jakarta.ee/specifications/servlet/6.0/jakarta-servlet-spec-6.0#request-attributes)" which implies that these may not be `null` in first place.

**Comment by skybber** [comment]
Thanks a lot for great explanation, we are using now customized version of FullAjaxExceptionhandler, that does not throw exception for non ajax request. So it seems that it is safe to do it in standard way.   We use a customized version because we need to eliminate the logging of exceptions originating from attacks—typically forged content-type and view state values, where Faces throw an IllegalArgumentException that cannot be filtered out because it is too general. The filter targets the exact location where the exception occurs, as this is the only reliable way to suppress it. I guess this is a common problem.

**Comment by BalusC** [comment]
Ok you're welcome. 

Note that the FullAjaxExceptionhandler won't be executed when the request did not hit the FacesServlet. Forged requests don't necessarily target the FacesServlet either. For this you'd need (a customized) FacesExceptionFilter.

**Comment by pizzi80** [comment]
@BalusC
your analysis potentially triggers at least 4 tickets in the various 
mojarra/myfaces/tomcat and servlet repositories :smiley: 

Probably fixing Tomcat should be the most convenient solution... ?

Question about Portlets: are still supported?

Googling a bit it seems that there is no Jakarta Spec,
this implies no future support and that the Jakarta Faces API
could be simplified ...?

**Comment by BalusC** [comment]
> Probably fixing Tomcat should be the most convenient solution... ?

Guess so. But I also want to improve Mojarra on that and take a second look at the Faces spec because in its current form it does not specify how exactly to detect this condition: "If the current request is an attempt by the servlet container to display a servlet error page".

And we still need to look how other servletcontainers behave in this regard. Do they fail the same way? Or is it only Tomcat?

> Question about Portlets: are still supported?

There are two surviving impls which are still alive: https://www.liferay.com and https://portals.apache.org/pluto/

> Googling a bit it seems that there is no Jakarta Spec, this implies no future support and that the Jakarta Faces API could be simplified ...?

It's indeed not part of JEE spec and has never been. It's a separate JSR, see also https://en.wikipedia.org/wiki/Java_Portlet_Specification for history and JSR numbers.

The JSF API was originally designed in such way that it has no hard Servlet API dependencies so it could be used on a Portlet runtime as well (and theoretically any other future non-Servlet/Portlet runtime). I think this level of abstractness/reusability is a very smart move so let's keep it as is.

**Comment by pizzi80** [comment]
> Guess so. But I also want to improve Mojarra on that and take a second look at the Faces spec because in its current form it does not specify how exactly to detect this condition: "If the current request is an attempt by the servlet container to display a servlet error page".

Absolutely +1

> And we still need to look how other servletcontainers behave in this regard. Do they fail the same way? Or is it only Tomcat?

Good question!



thanks also for the history recap! :heart_hands:

**Comment by pizzi80** [comment]
I opened an issue ticket for Tomcat

https://bz.apache.org/bugzilla/show_bug.cgi?id=69444

**Comment by pizzi80** [comment]
At Tomcat they said that we should rely 
on the following new attribute:

`jakarta.servlet.error.exception`

or check if old "message" request attribute is "present" 
(that is different to check if it's != null)

but I think it's slower because we have to iterate on 
`request.getAttributeNames` that is an old Java `Enumaration<String>`

to summatize, on Mojarra the best solution is to simply change:

`RestoreViewPhase.WEBAPP_ERROR_PAGE_MARKER = "jakarta.servlet.error.exception"`

**Comment by BalusC** [comment]
jakarta.servlet.error.exception is absent on non-exceptional errors such as 404, 400, etc so that's not a feasible way.

> or check if old "message" request attribute is "present"

I already checked, it was absent. I.e. request.getAttributeNames() didn't contain it.

**Comment by pizzi80** [comment]
very bad...

we also have another problem:

`RequestMap.containsKey` implementation is wrong
because it should not be:

`return get(key) != null`

**Comment by BalusC** [comment]
Indeed, already saw it.

**Comment by pizzi80** [comment]
what about

```
// 400, 404 errors have message but not exception
private static final String WEBAPP_ERROR_PAGE_MARKER = "jakarta.servlet.error.message";

// real exceptions (500) have the attribute "jakarta.servlet.error.exception" but not always the
// "jakarta.servlet.error.message" attribute, for example when the page is mapped with java.lang.Throwable
// and the exception has no message (throw new RuntimeException())
private static final String WEBAPP_ERROR_PAGE_MARKER_FALLBACK = "jakarta.servlet.error.exception";

private static boolean isErrorPage(FacesContext context) {
  final Map<String,Object> requestMap = context.getExternalContext().getRequestMap();
  return requestMap.containsKey(WEBAPP_ERROR_PAGE_MARKER)
         || requestMap.containsKey(WEBAPP_ERROR_PAGE_MARKER_FALLBACK);
}
```

**Comment by BalusC** [comment]
Indeed, we should check both. 

Please continue in Mojarra repo. This is not OmniFaces related. I realized I forgot to create ticket, so here it is https://github.com/eclipse-ee4j/mojarra/issues/5528
