### ISSUE TITLE
Add a property to @Param annotation like redirectOnValidationFailed

### ISSUE THREAD

**Issue by anadollu** [omnifaces/omnifaces#87]
Hi,
It is very nice to have an option to specify outcome for redirecting automatically when validation of parameter injected with @Param annotation was failed. 

For example 

```java

@Param( required = true, redirectOnValidationFailed = "/index.xhtml" )
private Long id;

```
when id param is null then redirect to index.html automatically. 

Thanks.

**Comment by arjantijms** [comment]
Might be a nice idea indeed, but we do have to realize that multiple parameters may be injected, and that a @PostConstruct method in the bean (if any) will still be called.

So in such method it may still be needed for code to check if validation has failed before. Furthermore, other beans in the same JSF phase will also still be injected and have to check for validation failed, etc.

A redirect will therefor not be as automatic as one may think. This is simply because there's no concept of all beans being injected first, then all @PostConstruct methods called, etc.

But let's think about this a little at least.

Thanks for your suggestion!

**Comment by anadollu** [comment]
Hımm, you are right. Anyway @PostConstruct will be called surely. And multiple params create confusion. 

I'll think about these points. [ Let's be creative :) ]

**Comment by anadollu** [comment]
And another case same parameter might be injected at multiple injection points.

**Comment by BalusC** [comment]
I'd rather not implement that.

Better "fall back" to `<f:viewParam>` + `<o:viewParamValidationFailed>`.
