### ISSUE TITLE
DefaultResourceHandler conflicts with PrimeFaces resource handler

### ISSUE THREAD

**Issue by DonatasC** [omnifaces/omnifaces#97]
My application (Omnifaces2.0+PrimeFaces5.1+PrimeFacesExtensions3.0) gets the following ResourceHandler chain during system startup:

GraphicResourceHandler -> PrimeFacesExtensionsResourceHandler -> PrimeResourceHandler

Issue - Primefaces version number is no longer appended to PrimeFaces resources; i.e. URL's used to be:

/javax.faces.resource/primefaces.js.html?ln=primefaces&v=5.1

now they are:

/javax.faces.resource/primefaces.js.html?ln=primefaces

Reason:

PrimeFacesExtensionsResourceHandler has overridden only 3 argument version of createResource(); PrimeResourceHandler has overriden ONLY 2 argument version of createResource(). 
JSF calls createResource with 2 arguments, your DefaultResourceHandler current implementation calls wrapped.createResource() with 3 arguments (!!!), but PrimeResourceHandler appends version number ONLY on 2 argument call.

Main issue: if JSF calls 2 argument version of createResource(), only 2 argument version must be called by all wrappers in the chain. DefaultResourceHandler breaks this (in case of Primefaces resources calls 3 argument version).

**Comment by BalusC** [comment]
Technically, the PrimeFaces resource handlers are broken. They should have implemented all 3 `createResource()` methods. 

The problem here is that the `DefaultResourceHandler` only looks at the directly wrapped resource handler. That directly wrapped resource handler is in turn responsible for calling the right `createResource()` method of its wrapped one. 

In an ideal world, everyone should be overriding all 3 `createResource()` methods, or be using `DefaultResourceHandler`'s approach. 

In any case, I'll brainstorm about fixing this peculiar problem from OmniFaces side on, although it's not OmniFaces' fault. In the meanwhile, you'd better also report it to PrimeFaces and PrimeFaces Extensions guys.

**Comment by BalusC** [comment]
I completely reworked the `DefaultResourceHandler`.

It's available in today's [2.1 SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.1-SNAPSHOT/). Can you give it a try and let me know?

**Comment by DonatasC** [comment]
Yes, 2.1-SNAPSHOT is working correctly, PrimeFaces version number is appended again.
Thank you very much for fast fix!

**Comment by DonatasC** [comment]
DefaultResourceHandler source code is very elegant now :) and is correct regarding argument number :)

**Comment by BalusC** [comment]
Great! Thank you for reporting.
